services:

  php:
    build: ./
    container_name: php-apache
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html      
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      # - ./apache/apache2.conf:/etc/apache2/apache2.conf
      # - ./apache/sites-enabled/000-default.conf:/etc/apache2/sites-enabled/000-test.conf      
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    restart: unless-stopped
    volumes:
      - mysqldata:/var/lib/mysql      
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8002:80
    environment:
      MYSQL_ROOT_PASSWORD: password
    # redis

volumes:
  mysqldata: